version: '3.7'

services:
  redis:
    image: redis:alpine
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
          
networks:
  backend: